language: node_js

node_js:
- "8"
- "9"

addons:
  sonarcloud:
    organization: "rbuas-github"

stages:
  - quality
  - compile
  - test
  - name: deploy
    if: branch = master

notifications:
  email:
    recipients:
    - rodrigobuas@gmail.com
    on_success: change
    on_failure: always

jobs:
  include:
    - name: lint
      stage: quality
      script: npm run lint

    - name: unit tests
      stage: test
      script:
        - npm run test
        - bash sonar.sh
